name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'auth/**'
      - 'msg/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [auth,msg]
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image

